/**
 * generate-supabase-seed.ts
 * Generates supabase/seed.sql from src/lib/mock-data.ts + the VRBO affiliate
 * link data in scripts/seed-*-links.mjs.
 *
 * Slug logic is an exact replica of src/db/seed.ts:
 *   title.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
 *
 * Usage:
 *   npx tsx scripts/generate-supabase-seed.ts
 */
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  initialProperties,
  initialArticles,
  ontarioListicleChalets,
} from '../src/lib/mock-data';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// Exact replica of the slug logic in src/db/seed.ts
const slugify = (title: string) =>
  title.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');

// Escape a JS string for a SQL single-quoted literal
const q = (v: string | null | undefined): string => {
  if (v === null || v === undefined) return 'NULL';
  return `'${v.replace(/'/g, "''")}'`;
};
const b = (v: boolean | undefined, dflt = false) =>
  v === undefined ? String(dflt) : String(v);
const n = (v: number | string | undefined, dflt: string | null = null) => {
  if (v === undefined || v === null || v === '') return dflt ?? 'NULL';
  return String(v);
};

const out: string[] = [];
out.push('-- seed.sql — generated by scripts/generate-supabase-seed.ts');
out.push('-- Source: src/lib/mock-data.ts + scripts/seed-*-links.mjs');
out.push('-- Applied by `supabase db reset` (see supabase/config.toml [db.seed]).');
out.push('');

// ---------------------------------------------------------------- users
// NOTE: admin login (src/lib/auth.ts) checks ADMIN_USERNAME / ADMIN_PASSWORD
// env vars via NextAuth credentials — NOT this table. This row exists only
// for completeness / foreign-key-free local testing.
const adminUser = process.env.ADMIN_USERNAME || 'admin';
out.push('-- users (mirrors .env ADMIN_USERNAME; auth itself uses env vars) --');
out.push(
  `INSERT INTO users (name, email, hashed_password, role) VALUES (${q(adminUser)}, ${q(`${adminUser}@cottageescape.ca`)}, 'LOCAL_DEV__USE_ENV_ADMIN_PASSWORD', 'admin') ON CONFLICT (email) DO NOTHING;`,
);
out.push('');

// ------------------------------------------------------------ properties
out.push('-- properties (6 mock cottages, stable ids 1-6) --');
for (const p of initialProperties) {
  out.push(
    `INSERT INTO properties (id, title, slug, location, province, price, rating, reviews, image, tag, description, is_liked, is_published) VALUES (${p.id}, ${q(p.title)}, ${q(slugify(p.title))}, ${q(p.location)}, ${q(p.province)}, ${n(p.price)}, ${q(p.rating)}, ${n(p.reviews, '0')}, ${q(p.image)}, ${q(p.tag)}, ${q(p.description)}, ${b(p.isLiked)}, true);`,
  );
}
out.push(
  `SELECT setval(pg_get_serial_sequence('properties', 'id'), COALESCE(MAX(id), 1)) FROM properties;`,
);
out.push('');

// -------------------------------------------------------------- articles
out.push('-- articles (2 standard + 1 listicle, stable ids from mock-data) --');
// lis[] mirrors the listicle article + items into supabase/seed-listicle-101.sql
// so import-public-sql.mjs can re-seed them after truncating articles
// (multi-line statements — must NOT be extracted line-by-line).
const lis: string[] = [
  '-- seed-listicle-101.sql — generated by scripts/generate-supabase-seed.ts',
  '-- Re-seeds mock listicle article 101 + its items (prod dump uses ids 1-15).',
  '',
];
for (const a of initialArticles) {
  const type = a.isListicle ? 'listicle' : 'standard';
  const stmt = `INSERT INTO articles (id, title, slug, type, content, excerpt, category, author, featured_image, is_published) VALUES (${a.id}, ${q(a.title)}, ${q(a.slug)}, '${type}', ${q(a.content)}, ${q(a.excerpt)}, ${q(a.category)}, 'Editorial Team', ${q(a.image)}, true);`;
  out.push(stmt);
  if (a.isListicle) lis.push(stmt);
}
const listicle = initialArticles.find((a) => a.isListicle);
if (!listicle) throw new Error('No listicle article found in mock-data');
out.push(
  `SELECT setval(pg_get_serial_sequence('articles', 'id'), COALESCE(MAX(id), 1)) FROM articles;`,
);
out.push('');

// -------------------------------------------------------- listicle_items
out.push(
  `-- listicle_items (7 chalets linked to listicle article id ${listicle.id}) --`,
);
for (const item of ontarioListicleChalets) {
  const stmt = `INSERT INTO listicle_items (article_id, rank, title, description, rating, price, image, vibe, vrbo_link) VALUES (${listicle.id}, ${item.rank}, ${q(item.title)}, ${q(item.description)}, ${q(item.rating)}, ${n(item.price)}, ${q(item.image)}, ${q(item.vibe)}, ${q(item.vrboLink)});`;
  out.push(stmt);
  lis.push(stmt);
}
out.push(
  `SELECT setval(pg_get_serial_sequence('listicle_items', 'id'), COALESCE(MAX(id), 1)) FROM listicle_items;`,
);
out.push('');

// ----------------------------------------------------------------- pages
out.push('-- pages (terms page, mirrors src/db/seed.ts) --');
out.push(
  `INSERT INTO pages (title, slug, template, is_published) VALUES ('Terms of Service & Affiliate Disclosure', 'terms', 'standard', true) ON CONFLICT (slug) DO NOTHING;`,
);
out.push('');

// ----------------------------------------------------------- search_links
const KEYWORDS = [
  'Luxury Cottages in',
  'Pet Friendly Cottages in',
  'Family Cottage Resort in',
  'Lakefront Cottage in',
  'Cottage with Hot Tub in',
  'Romantic Cottage for 2 in',
  'Cottage Rentals in',
  'Chalet for Rent in',
  'Cabin for Rent in',
  'Waterfront Cottage in',
  'Log Wood Cottage in',
  'Mountain Cottage in',
];

const PROVINCES: Array<{ city: string; url: string }> = [
  { city: 'Ontario', url: 'https://vrbo.com/affiliates/cottagerentals/ontario' },
  { city: 'Quebec', url: 'https://vrbo.com/affiliates/cottagerentals/quebec' },
  { city: 'British Columbia', url: 'https://vrbo.com/affiliates/cottagerentals/british-columbia' },
  { city: 'New Brunswick', url: 'https://vrbo.com/affiliates/cottagerentals/newbrunswick' },
  { city: 'Alberta', url: 'https://vrbo.com/affiliates/search-alberta-dateless.aQombZh' },
  { city: 'Nova Scotia', url: 'https://vrbo.com/affiliates/cottagerentals/novascotia' },
  { city: 'Manitoba', url: 'https://vrbo.com/affiliates/cottagerentals/manitoba' },
  { city: 'Saskatchewan', url: 'https://vrbo.com/affiliates/cottagerentals/saskatchewan' },
];

type City = { cityKey: string; label: string; url: string };
const CITIES: City[] = [
  // Ontario (scripts/seed-ontario-links.mjs)
  { cityKey: 'Muskoka', label: 'Muskoka', url: 'https://vrbo.com/affiliates/search-muskoka-lakes-dateless.i1p6qgQ' },
  { cityKey: 'Haliburton', label: 'Haliburton', url: 'https://vrbo.com/affiliates/search-haliburton-county-dateless.gko8ZuN' },
  { cityKey: 'The Kawarthas', label: 'the Kawarthas', url: 'https://vrbo.com/affiliates/search-kawartha-lakes-dateless.fVLi4tH' },
  { cityKey: 'Georgian Bay', label: 'Georgian Bay', url: 'https://vrbo.com/affiliates/search-georgian-bay-dateless.BtiLYDA' },
  { cityKey: 'Ottawa Valley', label: 'Ottawa Valley', url: 'https://vrbo.com/affiliates/search-ottawa-valley-dateless.FNS8k4T' },
  { cityKey: 'Rideau Lakes', label: 'Rideau Lakes', url: 'https://vrbo.com/affiliates/search-rideau-lakes-dateless.N069pfM' },
  { cityKey: 'Prince Edward County', label: 'Prince Edward County', url: 'https://vrbo.com/affiliates/search-prince-edward-dateless.aw8hFUC' },
  { cityKey: 'Algonquin Highlands', label: 'Algonquin', url: 'https://vrbo.com/affiliates/search-algonquin-highlands-dateless.PZNHaPL' },
  // Quebec (scripts/seed-quebec-links.mjs)
  { cityKey: 'The Laurentians', label: 'the Laurentians', url: 'https://vrbo.com/affiliates/search-laurentians-dateless.zLlua6K' },
  { cityKey: 'Eastern Townships', label: 'Eastern Townships', url: 'https://vrbo.com/affiliates/search-eastern-townships-dateless.1ISvhwl' },
  { cityKey: 'Charlevoix', label: 'Charlevoix', url: 'https://vrbo.com/affiliates/search-charlevoix-dateless.MfRTViD' },
  { cityKey: 'Lanaudière', label: 'Lanaudière', url: 'https://vrbo.com/affiliates/search-lanaudiere-dateless.8zSTXrM' },
  { cityKey: 'Québec City', label: 'Québec City', url: 'https://vrbo.com/affiliates/search-quebec-dateless.7UBbZWM' },
  { cityKey: 'Mont-Tremblant', label: 'Mont-Tremblant', url: 'https://vrbo.com/affiliates/search-monttremblant-dateless.imz3fJn' },
  { cityKey: 'Gaspé', label: 'Gaspé', url: 'https://vrbo.com/affiliates/search-gaspsielesdelamadeleine-dateless.U3Cr4my' },
  { cityKey: 'Saguenay', label: 'Saguenay', url: 'https://vrbo.com/affiliates/search-saguenaylacsaintjean-dateless.5wgAZ3b' },
  // British Columbia (scripts/seed-bc-links.mjs)
  { cityKey: 'Okanagan Valley', label: 'Okanagan Valley', url: 'https://vrbo.com/affiliates/search-okanagan-valley-dateless.Xa9StES' },
  { cityKey: 'Sunshine Coast', label: 'Sunshine Coast', url: 'https://vrbo.com/affiliates/search-sunshine-coast-regional-district-dateless.0BzC8NS' },
  { cityKey: 'Vancouver Island', label: 'Vancouver Island', url: 'https://vrbo.com/affiliates/search-vancouver-island-dateless.qlhpMzk' },
  { cityKey: 'Whistler', label: 'Whistler', url: 'https://vrbo.com/affiliates/search-whistler-dateless.eEIfD8E' },
  { cityKey: 'Tofino', label: 'Tofino', url: 'https://vrbo.com/affiliates/search-tofino-dateless.MThdFkJ' },
  { cityKey: 'Victoria', label: 'Victoria', url: 'https://vrbo.com/affiliates/search-victoria-dateless.HFEgINs' },
  { cityKey: 'Kelowna', label: 'Kelowna', url: 'https://vrbo.com/affiliates/search-kelowna-dateless.lzoTBp7' },
  { cityKey: 'Squamish', label: 'Squamish', url: 'https://vrbo.com/affiliates/search-squamish-dateless.kcd97Id' },
  // New Brunswick (scripts/seed-nb-links.mjs)
  { cityKey: 'St. Andrews', label: 'St. Andrews', url: 'https://vrbo.com/affiliates/search-st-andrews-dateless.ZbQzvPW' },
  { cityKey: 'Miramichi', label: 'Miramichi', url: 'https://vrbo.com/affiliates/search-miramichi-dateless.iqpnjzr' },
  { cityKey: 'Moncton', label: 'Moncton', url: 'https://vrbo.com/affiliates/search-moncton-dateless.6bfXPQW' },
  { cityKey: 'Fundy National Park', label: 'Fundy National Park', url: 'https://vrbo.com/affiliates/search-fundy-national-park-dateless.aG7ywCB' },
  { cityKey: 'Saint John', label: 'Saint John', url: 'https://vrbo.com/affiliates/search-saint-john-dateless.9brm1pF' },
  { cityKey: 'Fredericton', label: 'Fredericton', url: 'https://vrbo.com/affiliates/search-fredericton-dateless.OgfMwaw' },
  { cityKey: 'Acadian Peninsula', label: 'Acadian Peninsula', url: 'https://vrbo.com/affiliates/search-acadian-peninsula-dateless.bJ5LRJX' },
  { cityKey: 'Shediac', label: 'Shediac', url: 'https://vrbo.com/affiliates/search-shediac-dateless.1iVCiaR' },
  // Alberta (scripts/seed-ab-links.mjs)
  { cityKey: 'Kananaskis', label: 'Kananaskis', url: 'https://vrbo.com/affiliates/search-kananaskis-dateless.hpgeZVS' },
  { cityKey: 'Pigeon Lake', label: 'Pigeon Lake', url: 'https://vrbo.com/affiliates/search-pigeon-lake-dateless.JTYQEjI' },
  { cityKey: 'Banff', label: 'Banff', url: 'https://vrbo.com/affiliates/search-banff-dateless.uLSnrdE' },
  { cityKey: 'Jasper', label: 'Jasper', url: 'https://vrbo.com/affiliates/search-jasper-dateless.NWq6ZUd' },
  { cityKey: 'Lake Louise', label: 'Lake Louise', url: 'https://vrbo.com/affiliates/search-lake-louise-dateless.2e9ouLC' },
  { cityKey: 'Calgary', label: 'Calgary', url: 'https://vrbo.com/affiliates/search-edmonton-dateless.J66XrGc' },
  { cityKey: 'Edmonton', label: 'Edmonton', url: 'https://vrbo.com/affiliates/search-edmonton-dateless.J66XrGc' },
  { cityKey: 'Waterton Lakes', label: 'Waterton Lakes', url: 'https://vrbo.com/affiliates/search-waterton-park-dateless.i2udAza' },
  // Manitoba (scripts/seed-mb-links.mjs)
  { cityKey: 'Falcon Lake', label: 'Falcon Lake', url: 'https://vrbo.com/affiliates/search-falcon-lake-dateless.EZRGSfF' },
  { cityKey: 'West Hawk Lake', label: 'West Hawk Lake', url: 'https://vrbo.com/affiliates/search-west-hawk-lake-dateless.08Tj5Ia' },
  { cityKey: 'Winnipeg', label: 'Winnipeg', url: 'https://vrbo.com/affiliates/search-winnipeg-dateless.lxLe2Qs' },
  { cityKey: 'Clear Lake', label: 'Clear Lake', url: 'https://vrbo.com/affiliates/search-clear-lake-dateless.q9bd9Rq' },
  { cityKey: 'Lake Winnipeg', label: 'Lake Winnipeg', url: 'https://vrbo.com/affiliates/search-lake-winnipeg-dateless.vZZmRFn' },
  { cityKey: 'Gimli', label: 'Gimli', url: 'https://vrbo.com/affiliates/search-gimli-dateless.MTyODwD' },
  { cityKey: 'Whiteshell Provincial Park', label: 'Whiteshell Provincial Park', url: 'https://vrbo.com/affiliates/search-whiteshell-provincial-park-dateless.1ugFBUf' },
  { cityKey: 'Hecla', label: 'Hecla', url: 'https://vrbo.com/affiliates/search-hecla-island-dateless.TSaKXdE' },
  // Nova Scotia (scripts/seed-ns-links.mjs)
  { cityKey: 'Cape Breton', label: 'Cape Breton', url: 'https://vrbo.com/affiliates/search-cape-breton-island-dateless.XqJW1mV' },
  { cityKey: 'South Shore', label: 'South Shore', url: 'https://vrbo.com/affiliates/search-emerys-island-dateless.pydujVt' },
  { cityKey: 'Halifax', label: 'Halifax', url: 'https://vrbo.com/affiliates/search-halifax-dateless.tlYq8rf' },
  { cityKey: 'Lunenburg', label: 'Lunenburg', url: 'https://vrbo.com/affiliates/search-lunenburg-dateless.DsP0d02' },
  { cityKey: 'Annapolis Valley', label: 'Annapolis Valley', url: 'https://vrbo.com/affiliates/search-annapolis-valley-dateless.2qIgmji' },
  { cityKey: "Peggy's Cove", label: "Peggy's Cove", url: 'https://vrbo.com/affiliates/search-peggys-cove-dateless.vH3Hij0' },
  { cityKey: 'Wolfville', label: 'Wolfville', url: 'https://vrbo.com/affiliates/search-wolfville-dateless.RL8WuF1' },
  { cityKey: 'Digby', label: 'Digby', url: 'https://vrbo.com/affiliates/search-digby-dateless.2dz5zXd' },
  // PEI (scripts/seed-pei-links.mjs)
  { cityKey: 'North Shore', label: 'North Shore', url: 'https://vrbo.com/affiliates/search-north-shore-dateless.C2SX4R6' },
  { cityKey: 'Points East', label: 'Points East', url: 'https://vrbo.com/affiliates/search-points-east-dateless.nHbYrBj' },
  { cityKey: 'Charlottetown', label: 'Charlottetown', url: 'https://vrbo.com/affiliates/search-charlottetown-dateless.S2ZPAkj' },
  { cityKey: 'Cavendish', label: 'Cavendish', url: 'https://vrbo.com/affiliates/search-cavendish-dateless.D1mpLDS' },
  { cityKey: 'Prince Edward Island National Park', label: 'Prince Edward Island National Park', url: 'https://vrbo.com/affiliates/search-prince-edward-island-national-park-dateless.XzuIbIs' },
  { cityKey: 'Summerside', label: 'Summerside', url: 'https://vrbo.com/affiliates/search-summerside-dateless.iFOmoU0' },
  { cityKey: 'Brackley Beach', label: 'Brackley Beach', url: 'https://vrbo.com/affiliates/search-greenwich-dateless.NvLGv3v' },
  { cityKey: 'Greenwich', label: 'Greenwich', url: 'https://vrbo.com/affiliates/search-greenwich-dateless.NvLGv3v' },
  // Saskatchewan (scripts/seed-sk-links.mjs)
  { cityKey: 'Waskesiu Lake', label: 'Waskesiu Lake', url: 'https://vrbo.com/affiliates/search-waskesiu-lake-dateless.701bxVT' },
  { cityKey: 'Regina', label: 'Regina', url: 'https://vrbo.com/affiliates/search-regina-dateless.4ywFRvx' },
  { cityKey: 'Saskatoon', label: 'Saskatoon', url: 'https://vrbo.com/affiliates/search-saskatoon-dateless.CeTIdzD' },
  { cityKey: 'Prince Albert National Park', label: 'Prince Albert National Park', url: 'https://vrbo.com/affiliates/search-prince-albert-national-park-dateless.tD34rkl' },
  { cityKey: 'Lake Diefenbaker', label: 'Lake Diefenbaker', url: 'https://vrbo.com/affiliates/search-diefenbaker-lake-dateless.Ke4v9RX' },
  { cityKey: 'Cypress Hills', label: 'Cypress Hills', url: 'https://vrbo.com/affiliates/search-cypress-hills-treeosix-adventure-park-dateless.IeXDGjY' },
  { cityKey: 'Emma Lake', label: 'Emma Lake', url: 'https://vrbo.com/affiliates/search-emma-lake-dateless.pGFf0bM' },
  { cityKey: 'Moose Jaw', label: 'Moose Jaw', url: 'https://vrbo.com/affiliates/search-moose-jaw-dateless.SaL3fE4' },
];

let linkCount = 0;
out.push('-- search_links (province-level: 8 provinces x 12 keywords) --');
for (const p of PROVINCES) {
  for (const kw of KEYWORDS) {
    out.push(
      `INSERT INTO search_links (city, category, affiliate_url, platform, type) VALUES (${q(p.city)}, ${q(`${kw} ${p.city}`)}, ${q(p.url)}, 'vrbo', 'province');`,
    );
    linkCount++;
  }
}
out.push(`-- search_links (city-level: ${CITIES.length} cities x 12 keywords) --`);
for (const c of CITIES) {
  for (const kw of KEYWORDS) {
    out.push(
      `INSERT INTO search_links (city, category, affiliate_url, platform, type) VALUES (${q(c.cityKey)}, ${q(`${kw} ${c.label}`)}, ${q(c.url)}, 'vrbo', 'city');`,
    );
    linkCount++;
  }
}
out.push(
  `SELECT setval(pg_get_serial_sequence('search_links', 'id'), COALESCE(MAX(id), 1)) FROM search_links;`,
);
out.push('');

// ------------------------------------------------------ affiliatecottages
// Production catalogue (queried by src/lib/cottages.js + admin cottages).
// Mock rows mirror initialProperties; destination slugs/provinces match the
// search_links cities so local destination pages return data.
type AffiliateSeed = {
  propId: number;
  destSlug: string;
  token: string;
  type: string;
  featured: boolean;
  sleeps: number;
  bedrooms: number;
  bathrooms: number;
  lat: number;
  lng: number;
  amenities: string[];
  affiliateUrl: string;
};
const AFFILIATES: AffiliateSeed[] = [
  { propId: 1, destSlug: 'muskoka', token: 'tok-local-01', type: 'cottage', featured: true, sleeps: 8, bedrooms: 3, bathrooms: 2, lat: 45.0, lng: -79.4, amenities: ['Waterfront', 'Hot tub', 'Fireplace', 'Kid-friendly'], affiliateUrl: 'https://vrbo.com/affiliates/search-muskoka-lakes-dateless.i1p6qgQ' },
  { propId: 2, destSlug: 'mont-tremblant', token: 'tok-local-02', type: 'chalet', featured: true, sleeps: 6, bedrooms: 3, bathrooms: 2, lat: 46.1, lng: -74.6, amenities: ['Fireplace', 'Hot tub', 'Spa'], affiliateUrl: 'https://vrbo.com/affiliates/search-monttremblant-dateless.imz3fJn' },
  { propId: 3, destSlug: 'tofino', token: 'tok-local-03', type: 'cabin', featured: false, sleeps: 4, bedrooms: 2, bathrooms: 1, lat: 49.15, lng: -125.9, amenities: ['Secluded', 'Fireplace'], affiliateUrl: 'https://vrbo.com/affiliates/search-tofino-dateless.MThdFkJ' },
  { propId: 4, destSlug: 'whistler', token: 'tok-local-04', type: 'lodge', featured: true, sleeps: 10, bedrooms: 5, bathrooms: 4, lat: 50.1, lng: -122.95, amenities: ['Hot tub', 'Pool', 'Spa', 'Fireplace'], affiliateUrl: 'https://vrbo.com/affiliates/search-whistler-dateless.eEIfD8E' },
  { propId: 5, destSlug: 'haliburton', token: 'tok-local-05', type: 'cottage', featured: true, sleeps: 8, bedrooms: 4, bathrooms: 2, lat: 45.05, lng: -78.5, amenities: ['Waterfront', 'Beach access', 'Kid-friendly', 'Pet-friendly'], affiliateUrl: 'https://vrbo.com/affiliates/search-haliburton-county-dateless.gko8ZuN' },
  { propId: 6, destSlug: 'bruce-peninsula', token: 'tok-local-06', type: 'log cabin', featured: false, sleeps: 6, bedrooms: 2, bathrooms: 1, lat: 45.2, lng: -81.5, amenities: ['Secluded', 'Fireplace', 'Pet-friendly'], affiliateUrl: 'https://vrbo.com/affiliates/cottagerentals/ontario' },
];
const jq = (v: unknown): string => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
out.push('-- affiliatecottages (6 mock catalogue rows mirroring properties) --');
for (const a of AFFILIATES) {
  const p = initialProperties.find((x) => x.id === a.propId);
  if (!p) throw new Error(`mock property ${a.propId} not found`);
  out.push(
    `INSERT INTO affiliatecottages (id, property_token, slug, province, name, type, source, thumbnail, photos, lat, lng, price_cad, rating, reviews, sleeps, bedrooms, bathrooms, amenities, google_link, affiliate_url, is_featured, is_hidden, available, image_alt, last_synced) VALUES (${q(`${a.destSlug}-${a.token}`)}, ${q(a.token)}, ${q(a.destSlug)}, ${q(p.province)}, ${q(p.title)}, ${q(a.type)}, 'vrbo', ${q(p.image)}, ${jq([p.image])}, ${a.lat}, ${a.lng}, ${n(p.price)}, ${q(p.rating)}, ${n(p.reviews, '0')}, ${a.sleeps}, ${a.bedrooms}, ${a.bathrooms}, ${jq(a.amenities)}, ${q(`https://www.vrbo.com/search/keywords:${a.destSlug}`)}, ${q(a.affiliateUrl)}, ${a.featured}, false, true, ${q(p.title)}, CURRENT_DATE);`,
  );
}
out.push('');

const dest = join(root, 'supabase', 'seed.sql');
writeFileSync(dest, out.join('\n'), 'utf8');
const lisDest = join(root, 'supabase', 'seed-listicle-101.sql');
writeFileSync(lisDest, lis.join('\n') + '\n', 'utf8');
console.log(`Wrote ${dest} + ${lisDest}`);
console.log(
  `  properties=${initialProperties.length} articles=${initialArticles.length} listicle_items=${ontarioListicleChalets.length} search_links=${linkCount} affiliatecottages=${AFFILIATES.length}`,
);
